services:
  api-service:
    build: ./api-service
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./secrets/api_token.txt:/run/secrets/api_token
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  download-service:
    build: ./download-service
    environment:
      - REDIS_HOST=redis
    volumes:
      - download_data:/app/downloads
    depends_on:
      - redis

  telegram-service:
    build: ./telegram-service
    environment:
      - REDIS_HOST=redis
    volumes:
      - download_data:/app/downloads
      - ./secrets/telegram_token.txt:/run/secrets/telegram_token
    depends_on:
      - redis

volumes:
  download_data: