services:
  api-service:
    build: ./api-service
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./secrets/api_token.txt:/run/secrets/api_token
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"