services:
  api-service:
    image: eevarn/video-downloader-api:latest
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=${API_TOKEN}
    secrets:
      - api_token
    networks:
      - downloader

  download-service:
    image: eevarn/video-downloader-download:latest
    environment:
      - API_URL=http://api-service:8000
    depends_on:
      - api-service
    volumes:
      - download_data:/app/downloads
    networks:
      - downloader

  telegram-service:
    image: eevarn/video-downloader-telegram:latest
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=http://api-service:8000
    depends_on:
      - api-service
    secrets:
      - telegram_token
    volumes:
      - download_data:/app/downloads
    networks:
      - downloader

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - downloader
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


secrets:
  api_token:
    external: true
  telegram_token:
    external: true

volumes:
  download_data:

networks:
  downloader:
    driver: overlay
    attachable: true