services:
  api-service:
    image: eevarn/video-downloader-api:latest
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=${API_TOKEN}
    secrets:
      - api_token

  download-service:
    image: eevarn/video-downloader-download:latest
    environment:
      - API_URL=http://api-service:8000
    depends_on:
      - api-service

  telegram-service:
    image: eevarn/video-downloader-telegram:latest
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=http://api-service:8000
    depends_on:
      - api-service
    secrets:
      - telegram_token

secrets:
  api_token:
    external: true
  telegram_token:
    external: true
