services:
  api-service:
    image: eevarn/video-downloader-api:latest
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=${API_TOKEN}
    secrets:
      - api_token
    networks:
      - downloader
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  download-service:
    image: eevarn/video-downloader-download:latest
    environment:
      - API_URL=http://api-service:8000
      - HTTP_PROXY=socks5://shadowsocks-client:1080
      - HTTPS_PROXY=socks5://shadowsocks-client:1080
      - ALL_PROXY=socks5://shadowsocks-client:1080
    depends_on:
      - api-service
    volumes:
      - download_data:/app/downloads
    networks:
      - downloader
      - shadowsocks-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  telegram-service:
    image: eevarn/video-downloader-telegram:latest
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=http://api-service:8000
    depends_on:
      - api-service
    secrets:
      - telegram_token
    volumes:
      - download_data:/app/downloads
    networks:
      - downloader
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - downloader
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


secrets:
  api_token:
    external: true
  telegram_token:
    external: true

volumes:
  download_data:

networks:
  downloader:
    driver: overlay
    attachable: true
  shadowsocks-network:
    external:
      name: shadowsocks-network