services:
  api-service:
    image: eevarn/video-downloader-api:latest
    environment:
      - API_TOKEN=${API_TOKEN}
    ports:
      - "8000:8000"
    restart: on-failure

  telegram-service:
    image: eevarn/video-downloader-telegram:latest
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=http://api-service:8000
    volumes:
      - /home/ivan/downloads:/app/downloads
    depends_on:
      - api-service
    restart: on-failure

  download-service:
    image: eevarn/video-downloader-download:latest
    network_mode: host
    environment:
      - REDIS_HOST=127.0.0.1
    volumes:
      - /home/ivan/downloads:/app/downloads
    restart: on-failure

  cleanup-service:
    image: eevarn/video-downloader-cleanup:latest
    environment:
      - MAX_AGE_HOURS=1
      - CLEANUP_INTERVAL_SECONDS=600
    volumes:
      - /home/ivan/downloads:/app/downloads
    restart: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: on-failure

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    restart: on-failure

networks:
  default:
    driver: bridge
