services:
  api-service:
    image: eevarn/video-downloader-api:latest
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    environment:
      - REDIS_HOST=redis
    secrets:
      - api_token
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  download-service:
    image: eevarn/video-downloader-download:latest
    build:
      context: ./download-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    volumes:
      - download_data:/app/downloads
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  telegram-service:
    image: eevarn/video-downloader-telegram:latest
    build:
      context: ./telegram-service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    volumes:
      - download_data:/app/downloads
    secrets:
      - telegram_token
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  api_token:
    external: true
  telegram_token:
    external: true

volumes:
  download_data: