---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: video-downloader
spec:
  encryptedData:
    api_token: AgCfPF4nLyj99t46xyJxRqe+wTag56WC2rm0r1xL5e2sTNaLY0wT0qCWV+lsWDCQd2hdQKjGVUt/i43xc/6FQrdi3rFDgIPr6CfFVyYfFlpQjKkQY78KicOvVsxMQAEtze4s2GSvCgnSS/zJ7/xkD/w+idSQJiAEBzFOcSFD6kC2dvZnZX4XtbvI23nXEzcK3hz8GTSvn0l+NV2C/LMpX3Cdho3yYBMjsIwoJMeHe7EcU+Qvqr8HEmlCyiX0ddEAQCGKRxvo0lRwJM6XCzQd+vHTedieR1YUU4yqQNEjGzDvsJ2IlbPlYoo2X06DdSg57EC/bNX5jw2SXmvB3PX94ClkLd8tFCM2s+633MBR4+aDzPgRHv1o7uD8MbRAey8V7i981ZvE1O7Xk1Ef/gS0HGe96IbNCmhuFmdTRJnaUKx7YMgdvWPRsD6wNW9Afp1h/ZrqwnE/WooC6Ncic15KVqcSClZ6XKuPjqXxbZlBYbfg5WQHJ+JihbzfQJTryEtBf5zxTPbxbNzOQiq+9ltp5rAuoRClTzWfkcnC1RkvPHROWn06sKa9pcEP4Ae7BqhXMbiJ5af6dGhrfbJybFU+YIqocjHzYIem0m3pSX8X2nY1CPg/Rg2j4AIh9MHE7F9wMLde7BnXv7EJmWQgH9rGHJZUzHv0v0Bk/rsrkqFSItT4HEpQhdaKjVMwM9klrhQLTYvi1Sn0WM8wog==
    telegram_token: AgDYJg8FTwXaLtkYAkN5HnGz6lrPWcMxrJ43EyOcg34b/a4EV4Efq0lfaI9iApbld/mVi9YxCpy7unKXACL4fVgnxCTOjkCcSv7Xm2aRzy73G8n1ibfUZaznifES3x2XgC0rPWk9/mx5GRVbi/Dna8Yvdh2cCcMj1X5RWUu4mP4UnmrKT0NXnZaPvfe7NdKTWqln4FGpoP/UTDn3wH6bl2bmGEB4zNFFlunCJQSseeHjaS/EWXT8UuQ/cbG/gzEQsjDrkRoCP/Etzsygqijz/hsBbrXdXWHg4unXSNZYBXzHMAZLTmuLqKeWKXeWfSODTws5WLD7yOumJecitDc2l47ai3hOYAsQmAWCqkFlgCIi2lrR8chXuQ8Cj9IU2qi/esZA6UNQUR4Huw9DzWVvEWzf3DnluFj4yIhWccW4UV9HUZYf5Q7D8vynleFkol0brMeZ09BiNlMkeFhlNq+Y/mJVgfyW9sKxy3diWU++FLfZvOg2cGbE/+3m62m84hjdodUh4jvOPgWnnbpoEhyYfZkXZgm165CoBiwzVCB7t1H/GTs5cLBA8DciaazEuwc6zoTmdmvnfRlUO4d/bPdjruOOLDsXHbWhwhCyK8ncJumEA1Uz/Vch7iyeNxTeITz8Zx5jzGrkGBDzzLGviBrEK1rlEqEfNJGrB4MCT4OHFO3x5zvigmUPdNO9PslhlIzFrxm08VXvI6CjjC1t0UND2FxTAzRZA0/0+MmxSppPMlZ676j0h75xiXPsIqCTQYj6
  template:
    metadata:
      name: app-secrets
      namespace: video-downloader
    type: Opaque
