name: CI - Build and Push Docker Images

on: [push]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API service
        uses: docker/build-push-action@v4
        with:
          context: ./api-service
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/video-downloader-api:latest
          push: ${{ github.event_name == 'push' }}
          load: true

      - name: Build and push Download service
        uses: docker/build-push-action@v4
        with:
          context: ./download-service
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/video-downloader-download:latest
          push: ${{ github.event_name == 'push' }}
          load: true

      - name: Build and push Telegram service
        uses: docker/build-push-action@v4
        with:
          context: ./telegram-service
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/video-downloader-telegram:latest
          push: ${{ github.event_name == 'push' }}
          load: true
