name: CI - Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        docker compose build
        docker tag api-service $DOCKERHUB_USERNAME/video-downloader-api:latest
        docker tag download-service $DOCKERHUB_USERNAME/video-downloader-download:latest
        docker tag telegram-service $DOCKERHUB_USERNAME/video-downloader-telegram:latest
        docker push $DOCKERHUB_USERNAME/video-downloader-api:latest
        docker push $DOCKERHUB_USERNAME/video-downloader-download:latest
        docker push $DOCKERHUB_USERNAME/video-downloader-telegram:latest
